version: '2'
services:
   web:
      image: kchopein/aspnetcoresample
      ports: 
        - "80:5000"
      networks: 
        - testnetwork
      depends_on: 
        - mongodb
   mongodb:
      image: mongo
      ports: 
        - "27017:27017"
      networks: 
        - testnetwork
networks:
   testnetwork:
      driver: bridge
